# Generated by Django 2.2.7 on 2020-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200321_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='host',
            field=models.CharField(default='host', max_length=140),
        ),
    ]
