# Generated by Django 2.2.7 on 2020-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
    ]
